package js.parsing;

public final class Tokens {
  // Token Ids generated by 'dev dfa' tool (DO NOT EDIT BELOW)
  public static final int T_WS = 0;
  public static final int T_WORD = 1;
  public static final int T_SEMI = 2;
  // End of token Ids generated by 'dev dfa' tool (DO NOT EDIT ABOVE)
}
